In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)


In [9]:
arr2 = np.array([0,1,2,3,4,5])
arr2.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye(3)

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** 2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 1  4  9 16 25]


In [32]:
arr = np.array([1,2,3,4,5])
print(arr.sum())
print(np.sqrt(arr))
print(np.exp(arr))
print(np.mean(arr))
print(np.std(arr))



15
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
3.0
1.4142135623730951


In [34]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr[0]) 




[1 2 3]


In [37]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
mean = np.mean(data)
std_dev = np.std(data)
normalized_data  = (data-mean)/std_dev
print(normalized_data)


[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [41]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<8)]

array([6, 7])