In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    ' I am a developer ',
    'understanding the meaning of words',
    'your videos are good'
]

In [3]:
voc_size = 10000


In [4]:
one_hot_rep = [one_hot(words,voc_size) for words in sent] 

In [5]:
one_hot_rep

[[7355, 7908, 901, 3982],
 [7355, 7908, 901, 5034],
 [7355, 6591, 901, 5860],
 [8009, 3620, 2836, 4807],
 [5529, 7355, 2010, 901, 7166],
 [6220, 87, 2659, 1712]]

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sentence_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sentence_length)

In [11]:
embedded_docs

array([[   0,    0,    0,    0, 7355, 7908,  901, 3982],
       [   0,    0,    0,    0, 7355, 7908,  901, 5034],
       [   0,    0,    0,    0, 7355, 6591,  901, 5860],
       [   0,    0,    0,    0, 8009, 3620, 2836, 4807],
       [   0,    0,    0, 5529, 7355, 2010,  901, 7166],
       [   0,    0,    0,    0, 6220,   87, 2659, 1712]])

In [12]:
dim = 10


In [23]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sentence_length))
model.compile(optimizer='adam', loss='mse')

In [24]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 820ms/step


array([[[ 0.04866843, -0.0460887 ,  0.02519572,  0.01172513,
         -0.00707458,  0.04991651,  0.02192607,  0.02347001,
          0.02427829, -0.01217804],
        [ 0.04866843, -0.0460887 ,  0.02519572,  0.01172513,
         -0.00707458,  0.04991651,  0.02192607,  0.02347001,
          0.02427829, -0.01217804],
        [ 0.04866843, -0.0460887 ,  0.02519572,  0.01172513,
         -0.00707458,  0.04991651,  0.02192607,  0.02347001,
          0.02427829, -0.01217804],
        [ 0.04866843, -0.0460887 ,  0.02519572,  0.01172513,
         -0.00707458,  0.04991651,  0.02192607,  0.02347001,
          0.02427829, -0.01217804],
        [-0.01802689,  0.00966452,  0.01209838, -0.03922789,
         -0.00860142,  0.0142053 ,  0.03984067, -0.04667875,
          0.02499421,  0.01460523],
        [ 0.0004182 , -0.02646909, -0.04390517,  0.04066527,
          0.0245399 , -0.02658997, -0.01498228, -0.01696939,
         -0.03949237,  0.01752504],
        [ 0.04505055,  0.04444224,  0.00492326, -0.0

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0, 7355, 7908,  901, 3982])

In [27]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


array([[ 0.04866843, -0.0460887 ,  0.02519572,  0.01172513, -0.00707458,
         0.04991651,  0.02192607,  0.02347001,  0.02427829, -0.01217804],
       [ 0.04866843, -0.0460887 ,  0.02519572,  0.01172513, -0.00707458,
         0.04991651,  0.02192607,  0.02347001,  0.02427829, -0.01217804],
       [ 0.04866843, -0.0460887 ,  0.02519572,  0.01172513, -0.00707458,
         0.04991651,  0.02192607,  0.02347001,  0.02427829, -0.01217804],
       [ 0.04866843, -0.0460887 ,  0.02519572,  0.01172513, -0.00707458,
         0.04991651,  0.02192607,  0.02347001,  0.02427829, -0.01217804],
       [-0.01802689,  0.00966452,  0.01209838, -0.03922789, -0.00860142,
         0.0142053 ,  0.03984067, -0.04667875,  0.02499421,  0.01460523],
       [ 0.0004182 , -0.02646909, -0.04390517,  0.04066527,  0.0245399 ,
        -0.02658997, -0.01498228, -0.01696939, -0.03949237,  0.01752504],
       [ 0.04505055,  0.04444224,  0.00492326, -0.01414454,  0.03515079,
         0.04479008,  0.03901483,  0.03879045