In [1]:
import numpy as np

In [34]:
arr1 = np.arange(0,20,1).reshape(4,5)
array = np.random.randint(1, 21, size=(5, 5))

np.fill_diagonal(array, 1)

arr2 = np.arange(0,16,1).reshape(4,4)
np.fill_diagonal(arr2, 1)
arr2


array([[ 1,  1,  2,  3],
       [ 4,  1,  6,  7],
       [ 8,  9,  1, 11],
       [12, 13, 14,  1]])

In [40]:
arrs = np.arange(0,36).reshape(6,6)
arrs[:,2:4]

array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]])

In [21]:
import numpy as np
array1 = np.random.randint(1, 21, size=(3, 4))

# Create the second 3x4 array filled with random integers between 1 and 20
array2 = np.random.randint(1, 21, size=(3, 4))
print(array1 , "\n\n", array2)

[[15 18  4 16]
 [ 1  8 11 15]
 [15 14 11 12]] 

 [[10 11  3  6]
 [ 2 18 16  4]
 [10  3  2 13]]


In [38]:
five = np.random.randint(1, 21, size=(5,5))
print(five.std())

5.025693981929262


In [40]:
arrs = np.arange(0,36).reshape(6,6)
mean = arrs.mean()
std = arrs.std()
normalize = (arrs-mean)/std
normalize


array([[-1.68458833, -1.58832614, -1.49206395, -1.39580176, -1.29953957,
        -1.20327738],
       [-1.10701519, -1.010753  , -0.91449081, -0.81822862, -0.72196643,
        -0.62570424],
       [-0.52944205, -0.43317986, -0.33691767, -0.24065548, -0.14439329,
        -0.0481311 ],
       [ 0.0481311 ,  0.14439329,  0.24065548,  0.33691767,  0.43317986,
         0.52944205],
       [ 0.62570424,  0.72196643,  0.81822862,  0.91449081,  1.010753  ,
         1.10701519],
       [ 1.20327738,  1.29953957,  1.39580176,  1.49206395,  1.58832614,
         1.68458833]])

In [42]:
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]  # 'U10' for strings (max length 10), 'i4' for integers, 'f4' for floats

# Step 2: Create the structured array with some data
data = np.array([('Alice', 25, 60.5),
                 ('Bob', 30, 75.2),
                 ('Charlie', 22, 80.0),
                 ('David', 35, 70.1)],
                dtype=dtype)

# Step 3: Sort the array by the 'age' field

sorted_data = np.sort(data, order='age')

sorted_data

array([('Charlie', 22, 80. ), ('Alice', 25, 60.5), ('Bob', 30, 75.2),
       ('David', 35, 70.1)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [44]:
import numpy.ma as ma

# Step 1: Create a random integer array of shape (3, 3)
arr = np.random.randint(1, 10, size=(3, 3))

# Step 2: Mask the diagonal elements
mask = np.eye(3, dtype=bool)  # This creates a boolean mask for the diagonal
masked_arr = ma.masked_array(arr, mask=mask)

# Step 3: Compute the mean of the unmasked elements
mean_value = masked_arr.mean()

# Step 4: Replace the masked elements (diagonal) with the mean of the unmasked elements
masked_arr[mask] = mean_value

# Print the original and modified masked array
print("Original Array:")
print(arr)
print("\nMasked Array with Diagonal Masked and Replaced by Mean:")
print(masked_arr)

Original Array:
[[5 1 9]
 [4 5 9]
 [2 8 5]]

Masked Array with Diagonal Masked and Replaced by Mean:
[[5 1 9]
 [4 5 9]
 [2 8 5]]


In [45]:
example = np.random.randint(1, 10, size=(3, 3))